/* Slot Array generated by ARTSLotArray.java */

const int eoS = 0;
const int epsilon = 3;
const int startSymbol = 4;
const int firstSlotNumber = 6;
const char* symbolStrings[21] = {
  "$",	// 0
  "SIMPLE_WHITESPACE",	// 1
  "b",	// 2
  "#",	// 3
  "ART_AUGMENTED",	// 4
  "S",	// 5
  "Production ART_AUGMENTED ::= S ",	// 6
  "ART_AUGMENTED ::= . S ",	// 7
  "ART_AUGMENTED ::= S .",	// 8
  "Production S ::= S S S ",	// 9
  "S ::= . S S S ",	// 10
  "S ::= S . S S ",	// 11
  "S ::= S S . S ",	// 12
  "S ::= S S S .",	// 13
  "Production S ::= S S ",	// 14
  "S ::= . S S ",	// 15
  "S ::= S . S ",	// 16
  "S ::= S S .",	// 17
  "Production S ::= 'b'  ",	// 18
  "S ::= . 'b'  ",	// 19
  "S ::= 'b'  .",	// 20
};

const int slotIndex4[2] = {6,0,};
const int slotIndex5[4] = {9,14,18,0,};
const int* slotIndex[6] = {
  0,
  0,
  0,
  0,
  slotIndex4,
  slotIndex5,
};

const int slotRightSymbols[21] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5,
  0,
  0,
  5,
  5,
  5,
  0,
  0,
  5,
  5,
  0,
  0,
  2,
  0,
};

const int slotLHSSymbols[21] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  4,
  4,
  0,
  5,
  5,
  5,
  5,
  0,
  5,
  5,
  5,
  0,
  5,
  5,
};

const int slotGuardSetAddresses[21] = {
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  3,
  0,
  2,
  2,
  2,
  5,
  0,
  2,
  2,
  5,
  0,
  6,
  5,
};

const bool mergedSets[7][6] = {
  {
    false,
    false,
    false,
    false,
    false,
    false,
  },
  {
    false,
    false,
    false,
    false,
    false,
    false,
  },
  {
    false,
    false,
    true,
    false,
    false,
    true,
  },
  {
    true,
    false,
    false,
    false,
    false,
    false,
  },
  {
    false,
    false,
    false,
    true,
    false,
    false,
  },
  {
    true,
    false,
    true,
    false,
    false,
    true,
  },
  {
    false,
    false,
    true,
    false,
    false,
    false,
  },
};
