package uk.ac.rhul.cs.csle.art.cfg.lexer;

// @formatter:off
public enum LexemeKind {
  CHARACTER,
  SINGLETON_CASE_SENSITIVE,
  SINGLETON_CASE_INSENSITIVE,
  ID,
  INTEGER,
  SIGNED_INTEGER,
  AP_INTEGER,
  REAL,
  SIGNED_REAL,
  AP_REAL,
  CHAR_BQ,

  STRING_SQ,
  STRING_DQ,
  STRING_PLAIN_SQ,
  STRING_BRACE_NEST,
  STRING_BRACKET_NEST,
  STRING_DOLLAR,
  STRING_SHRIEK_SHRIEK,
  SIMPLE_WHITESPACE,

  COMMENT_LINE_C,
  COMMENT_BLOCK_C,
  COMMENT_NEST_ART,

  SML_COMMENT,
  SML_D,
  SML_INT,
  SML_WORD,
  SML_REAL,
  SML_CHAR,
  SML_STRING,
  SML_VID,
  SML_TYVAR,
  SML_TYCON,
  SML_LAB,
  SML_STRID,
  SML_SYMID
}
