/*******************************************************************************
*
* Parser generated by RDP on Nov 01 2019 15:54:44 from java_lex.bnf
*
*******************************************************************************/
#include <time.h>
#include "java_lex.h"

char
  *rdp_sourcefilename,          /* current source file name */
  **rdp_sourcefilenames,        /* array of source file names */
  *rdp_outputfilename = "java_lex.out";         /* output file name */

int
  rdp_symbol_echo = 0,                 /* symbol echo flag */
  rdp_verbose = 0,                     /* verbosity flag */
  rdp_sourcefilenumber,                /* Source file counter */
  rdp_pass;                            /* pass number */

int rdp_error_return = 0;              /* return value for main routine */

char *rdp_tokens = "IGNORE\0" 
"ID\0" "INTEGER\0" "REAL\0" "CHAR\0" "CHAR_ESC\0" "STRING\0" "STRING_ESC\0" "COMMENT\0" 
"COMMENT_VISIBLE\0" "COMMENT_NEST\0" "COMMENT_NEST_VISIBLE\0" "COMMENT_LINE\0" "COMMENT_LINE_VISIBLE\0" "EOF\0" "EOLN\0" "'!'\0" 
"'!='\0" "'\"'\0" "'%'\0" "'%='\0" "'&'\0" "'&&'\0" "'&='\0" "'\''\0" 
"'('\0" "')'\0" "'*'\0" "'*='\0" "'+'\0" "'++'\0" "'+='\0" "','\0" 
"'-'\0" "'--'\0" "'-='\0" "'.'\0" "'..'\0" "'...'\0" "'/'\0" "'/='\0" 
"':'\0" "';'\0" "'<'\0" "'<<'\0" "'<<='\0" "'<='\0" "'='\0" "'=='\0" 
"'>'\0" "'>='\0" "'>>'\0" "'>>='\0" "'>>>'\0" "'>>>='\0" "'?'\0" "'@'\0" 
"'A'\0" "'An'\0" "'Ann'\0" "'Anno'\0" "'Annot'\0" "'Annota'\0" "'Annotat'\0" "'Annotati'\0" 
"'Annotatio'\0" "'Annotation'\0" "'AnnotationM'\0" "'AnnotationMe'\0" "'AnnotationMet'\0" "'AnnotationMeth'\0" "'AnnotationMetho'\0" "'AnnotationMethod'\0" 
"'AnnotationMethodO'\0" "'AnnotationMethodOr'\0" "'AnnotationMethodOrC'\0" "'AnnotationMethodOrCo'\0" "'AnnotationMethodOrCon'\0" "'AnnotationMethodOrCons'\0" "'AnnotationMethodOrConst'\0" "'AnnotationMethodOrConsta'\0" 
"'AnnotationMethodOrConstan'\0" "'AnnotationMethodOrConstant'\0" "'AnnotationMethodOrConstantR'\0" "'AnnotationMethodOrConstantRe'\0" "'AnnotationMethodOrConstantRes'\0" "'AnnotationMethodOrConstantRest'\0" "'AnnotationMethodOrConstantRest;'\0" "'BooleanLiteral'\0" 
"'CharacterLiteral'\0" "'Expressions'\0" "'FloatingPointLiteral'\0" "'Fo'\0" "'For'\0" "'ForI'\0" "'ForIn'\0" "'ForIni'\0" 
"'ForInit'\0" "'ForInit;'\0" "'ForUpdate'\0" "'FormalParameter'\0" "'IDENTIFIER'\0" "'IntegerLiteral'\0" "'NullLiteral'\0" "'StringLiteral'\0" 
"'TypeName'\0" "'V'\0" "'Va'\0" "'Var'\0" "'Vari'\0" "'Varia'\0" "'Variab'\0" "'Variabl'\0" 
"'Variable'\0" "'VariableD'\0" "'VariableDe'\0" "'VariableDec'\0" "'VariableDecl'\0" "'VariableDecla'\0" "'VariableDeclar'\0" "'VariableDeclara'\0" 
"'VariableDeclarat'\0" "'VariableDeclarato'\0" "'VariableDeclarator'\0" "'VariableDeclarators'\0" "'VariableDeclaratorsR'\0" "'VariableDeclaratorsRe'\0" "'VariableDeclaratorsRes'\0" "'VariableDeclaratorsRest'\0" 
"'VariableDeclaratorsRest;'\0" "'['\0" "']'\0" "'^'\0" "'^='\0" "'abstract'\0" "'assert'\0" "'boolean'\0" 
"'break'\0" "'byte'\0" "'case'\0" "'catch'\0" "'char'\0" "'class'\0" "'continue'\0" "'default'\0" 
"'do'\0" "'double'\0" "'else'\0" "'enum'\0" "'extends'\0" "'final'\0" "'finally'\0" "'float'\0" 
"'for'\0" "'if'\0" "'implements'\0" "'import'\0" "'instanceof'\0" "'int'\0" "'interface'\0" "'long'\0" 
"'native'\0" "'new'\0" "'package'\0" "'private'\0" "'protected'\0" "'public'\0" "'return'\0" "'short'\0" 
"'static'\0" "'strictfp'\0" "'super'\0" "'switch'\0" "'synchronized'\0" "'this'\0" "'throw'\0" "'throws'\0" 
"'transient'\0" "'try'\0" "'void'\0" "'void.'\0" "'void.c'\0" "'void.cl'\0" "'void.cla'\0" "'void.clas'\0" 
"'void.class'\0" "'volatile'\0" "'while'\0" "'{'\0" "'|'\0" "'}'\0" "'~'\0" ;


/* Load keywords */
static void rdp_load_keywords(void)
{
  scan_load_keyword("!", NULL, RDP_T_33 /* ! */, SCAN_P_IGNORE);
  scan_load_keyword("!=", NULL, RDP_T_3361 /* != */, SCAN_P_IGNORE);
  scan_load_keyword("\"", "\\", RDP_T_34 /* " */, SCAN_P_STRING_ESC);
  scan_load_keyword("%", NULL, RDP_T_37 /* % */, SCAN_P_IGNORE);
  scan_load_keyword("%=", NULL, RDP_T_3761 /* %= */, SCAN_P_IGNORE);
  scan_load_keyword("&", NULL, RDP_T_38 /* & */, SCAN_P_IGNORE);
  scan_load_keyword("&&", NULL, RDP_T_3838 /* && */, SCAN_P_IGNORE);
  scan_load_keyword("&=", NULL, RDP_T_3861 /* &= */, SCAN_P_IGNORE);
  scan_load_keyword("\'", "\\", RDP_T_39 /* ' */, SCAN_P_STRING_ESC);
  scan_load_keyword("(", NULL, RDP_T_40 /* ( */, SCAN_P_IGNORE);
  scan_load_keyword(")", NULL, RDP_T_41 /* ) */, SCAN_P_IGNORE);
  scan_load_keyword("*", NULL, RDP_T_42 /* * */, SCAN_P_IGNORE);
  scan_load_keyword("*=", NULL, RDP_T_4261 /* *= */, SCAN_P_IGNORE);
  scan_load_keyword("+", NULL, RDP_T_43 /* + */, SCAN_P_IGNORE);
  scan_load_keyword("++", NULL, RDP_T_4343 /* ++ */, SCAN_P_IGNORE);
  scan_load_keyword("+=", NULL, RDP_T_4361 /* += */, SCAN_P_IGNORE);
  scan_load_keyword(",", NULL, RDP_T_44 /* , */, SCAN_P_IGNORE);
  scan_load_keyword("-", NULL, RDP_T_45 /* - */, SCAN_P_IGNORE);
  scan_load_keyword("--", NULL, RDP_T_4545 /* -- */, SCAN_P_IGNORE);
  scan_load_keyword("-=", NULL, RDP_T_4561 /* -= */, SCAN_P_IGNORE);
  scan_load_keyword(".", NULL, RDP_T_46 /* . */, SCAN_P_IGNORE);
  scan_load_keyword("..", NULL, RDP_T_4646 /* .. */, SCAN_P_IGNORE);
  scan_load_keyword("...", NULL, RDP_T_464646 /* ... */, SCAN_P_IGNORE);
  scan_load_keyword("/", NULL, RDP_T_47 /* / */, SCAN_P_IGNORE);
  scan_load_keyword("/=", NULL, RDP_T_4761 /* /= */, SCAN_P_IGNORE);
  scan_load_keyword(":", NULL, RDP_T_58 /* : */, SCAN_P_IGNORE);
  scan_load_keyword(";", NULL, RDP_T_59 /* ; */, SCAN_P_IGNORE);
  scan_load_keyword("<", NULL, RDP_T_60 /* < */, SCAN_P_IGNORE);
  scan_load_keyword("<<", NULL, RDP_T_6060 /* << */, SCAN_P_IGNORE);
  scan_load_keyword("<<=", NULL, RDP_T_606061 /* <<= */, SCAN_P_IGNORE);
  scan_load_keyword("<=", NULL, RDP_T_6061 /* <= */, SCAN_P_IGNORE);
  scan_load_keyword("=", NULL, RDP_T_61 /* = */, SCAN_P_IGNORE);
  scan_load_keyword("==", NULL, RDP_T_6161 /* == */, SCAN_P_IGNORE);
  scan_load_keyword(">", NULL, RDP_T_62 /* > */, SCAN_P_IGNORE);
  scan_load_keyword(">=", NULL, RDP_T_6261 /* >= */, SCAN_P_IGNORE);
  scan_load_keyword(">>", NULL, RDP_T_6262 /* >> */, SCAN_P_IGNORE);
  scan_load_keyword(">>=", NULL, RDP_T_626261 /* >>= */, SCAN_P_IGNORE);
  scan_load_keyword(">>>", NULL, RDP_T_626262 /* >>> */, SCAN_P_IGNORE);
  scan_load_keyword(">>>=", NULL, RDP_T_62626261 /* >>>= */, SCAN_P_IGNORE);
  scan_load_keyword("?", NULL, RDP_T_63 /* ? */, SCAN_P_IGNORE);
  scan_load_keyword("@", NULL, RDP_T_64 /* @ */, SCAN_P_IGNORE);
  scan_load_keyword("A", NULL, RDP_T_A, SCAN_P_IGNORE);
  scan_load_keyword("An", NULL, RDP_T_An, SCAN_P_IGNORE);
  scan_load_keyword("Ann", NULL, RDP_T_Ann, SCAN_P_IGNORE);
  scan_load_keyword("Anno", NULL, RDP_T_Anno, SCAN_P_IGNORE);
  scan_load_keyword("Annot", NULL, RDP_T_Annot, SCAN_P_IGNORE);
  scan_load_keyword("Annota", NULL, RDP_T_Annota, SCAN_P_IGNORE);
  scan_load_keyword("Annotat", NULL, RDP_T_Annotat, SCAN_P_IGNORE);
  scan_load_keyword("Annotati", NULL, RDP_T_Annotati, SCAN_P_IGNORE);
  scan_load_keyword("Annotatio", NULL, RDP_T_Annotatio, SCAN_P_IGNORE);
  scan_load_keyword("Annotation", NULL, RDP_T_Annotation, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationM", NULL, RDP_T_AnnotationM, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMe", NULL, RDP_T_AnnotationMe, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMet", NULL, RDP_T_AnnotationMet, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMeth", NULL, RDP_T_AnnotationMeth, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMetho", NULL, RDP_T_AnnotationMetho, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethod", NULL, RDP_T_AnnotationMethod, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodO", NULL, RDP_T_AnnotationMethodO, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOr", NULL, RDP_T_AnnotationMethodOr, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrC", NULL, RDP_T_AnnotationMethodOrC, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrCo", NULL, RDP_T_AnnotationMethodOrCo, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrCon", NULL, RDP_T_AnnotationMethodOrCon, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrCons", NULL, RDP_T_AnnotationMethodOrCons, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConst", NULL, RDP_T_AnnotationMethodOrConst, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConsta", NULL, RDP_T_AnnotationMethodOrConsta, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstan", NULL, RDP_T_AnnotationMethodOrConstan, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstant", NULL, RDP_T_AnnotationMethodOrConstant, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstantR", NULL, RDP_T_AnnotationMethodOrConstantR, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstantRe", NULL, RDP_T_AnnotationMethodOrConstantRe, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstantRes", NULL, RDP_T_AnnotationMethodOrConstantRes, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstantRest", NULL, RDP_T_AnnotationMethodOrConstantRest, SCAN_P_IGNORE);
  scan_load_keyword("AnnotationMethodOrConstantRest;", NULL, RDP_T_6511011011111697116105111110771011161041111007911467111110115116971101168210111511659 /* AnnotationMethodOrConstantRest; */, SCAN_P_IGNORE);
  scan_load_keyword("BooleanLiteral", NULL, RDP_T_BooleanLiteral, SCAN_P_IGNORE);
  scan_load_keyword("CharacterLiteral", NULL, RDP_T_CharacterLiteral, SCAN_P_IGNORE);
  scan_load_keyword("Expressions", NULL, RDP_T_Expressions, SCAN_P_IGNORE);
  scan_load_keyword("FloatingPointLiteral", NULL, RDP_T_FloatingPointLiteral, SCAN_P_IGNORE);
  scan_load_keyword("Fo", NULL, RDP_T_Fo, SCAN_P_IGNORE);
  scan_load_keyword("For", NULL, RDP_T_For, SCAN_P_IGNORE);
  scan_load_keyword("ForI", NULL, RDP_T_ForI, SCAN_P_IGNORE);
  scan_load_keyword("ForIn", NULL, RDP_T_ForIn, SCAN_P_IGNORE);
  scan_load_keyword("ForIni", NULL, RDP_T_ForIni, SCAN_P_IGNORE);
  scan_load_keyword("ForInit", NULL, RDP_T_ForInit, SCAN_P_IGNORE);
  scan_load_keyword("ForInit;", NULL, RDP_T_701111147311010511659 /* ForInit; */, SCAN_P_IGNORE);
  scan_load_keyword("ForUpdate", NULL, RDP_T_ForUpdate, SCAN_P_IGNORE);
  scan_load_keyword("FormalParameter", NULL, RDP_T_FormalParameter, SCAN_P_IGNORE);
  scan_load_keyword("IDENTIFIER", NULL, RDP_T_IDENTIFIER, SCAN_P_IGNORE);
  scan_load_keyword("IntegerLiteral", NULL, RDP_T_IntegerLiteral, SCAN_P_IGNORE);
  scan_load_keyword("NullLiteral", NULL, RDP_T_NullLiteral, SCAN_P_IGNORE);
  scan_load_keyword("StringLiteral", NULL, RDP_T_StringLiteral, SCAN_P_IGNORE);
  scan_load_keyword("TypeName", NULL, RDP_T_TypeName, SCAN_P_IGNORE);
  scan_load_keyword("V", NULL, RDP_T_V, SCAN_P_IGNORE);
  scan_load_keyword("Va", NULL, RDP_T_Va, SCAN_P_IGNORE);
  scan_load_keyword("Var", NULL, RDP_T_Var, SCAN_P_IGNORE);
  scan_load_keyword("Vari", NULL, RDP_T_Vari, SCAN_P_IGNORE);
  scan_load_keyword("Varia", NULL, RDP_T_Varia, SCAN_P_IGNORE);
  scan_load_keyword("Variab", NULL, RDP_T_Variab, SCAN_P_IGNORE);
  scan_load_keyword("Variabl", NULL, RDP_T_Variabl, SCAN_P_IGNORE);
  scan_load_keyword("Variable", NULL, RDP_T_Variable, SCAN_P_IGNORE);
  scan_load_keyword("VariableD", NULL, RDP_T_VariableD, SCAN_P_IGNORE);
  scan_load_keyword("VariableDe", NULL, RDP_T_VariableDe, SCAN_P_IGNORE);
  scan_load_keyword("VariableDec", NULL, RDP_T_VariableDec, SCAN_P_IGNORE);
  scan_load_keyword("VariableDecl", NULL, RDP_T_VariableDecl, SCAN_P_IGNORE);
  scan_load_keyword("VariableDecla", NULL, RDP_T_VariableDecla, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclar", NULL, RDP_T_VariableDeclar, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclara", NULL, RDP_T_VariableDeclara, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclarat", NULL, RDP_T_VariableDeclarat, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclarato", NULL, RDP_T_VariableDeclarato, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclarator", NULL, RDP_T_VariableDeclarator, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclarators", NULL, RDP_T_VariableDeclarators, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclaratorsR", NULL, RDP_T_VariableDeclaratorsR, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclaratorsRe", NULL, RDP_T_VariableDeclaratorsRe, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclaratorsRes", NULL, RDP_T_VariableDeclaratorsRes, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclaratorsRest", NULL, RDP_T_VariableDeclaratorsRest, SCAN_P_IGNORE);
  scan_load_keyword("VariableDeclaratorsRest;", NULL, RDP_T_86971141059798108101681019910897114971161111141158210111511659 /* VariableDeclaratorsRest; */, SCAN_P_IGNORE);
  scan_load_keyword("[", NULL, RDP_T_91 /* [ */, SCAN_P_IGNORE);
  scan_load_keyword("]", NULL, RDP_T_93 /* ] */, SCAN_P_IGNORE);
  scan_load_keyword("^", NULL, RDP_T_94 /* ^ */, SCAN_P_IGNORE);
  scan_load_keyword("^=", NULL, RDP_T_9461 /* ^= */, SCAN_P_IGNORE);
  scan_load_keyword("abstract", NULL, RDP_T_abstract, SCAN_P_IGNORE);
  scan_load_keyword("assert", NULL, RDP_T_assert, SCAN_P_IGNORE);
  scan_load_keyword("boolean", NULL, RDP_T_boolean, SCAN_P_IGNORE);
  scan_load_keyword("break", NULL, RDP_T_break, SCAN_P_IGNORE);
  scan_load_keyword("byte", NULL, RDP_T_byte, SCAN_P_IGNORE);
  scan_load_keyword("case", NULL, RDP_T_case, SCAN_P_IGNORE);
  scan_load_keyword("catch", NULL, RDP_T_catch, SCAN_P_IGNORE);
  scan_load_keyword("char", NULL, RDP_T_char, SCAN_P_IGNORE);
  scan_load_keyword("class", NULL, RDP_T_class, SCAN_P_IGNORE);
  scan_load_keyword("continue", NULL, RDP_T_continue, SCAN_P_IGNORE);
  scan_load_keyword("default", NULL, RDP_T_default, SCAN_P_IGNORE);
  scan_load_keyword("do", NULL, RDP_T_do, SCAN_P_IGNORE);
  scan_load_keyword("double", NULL, RDP_T_double, SCAN_P_IGNORE);
  scan_load_keyword("else", NULL, RDP_T_else, SCAN_P_IGNORE);
  scan_load_keyword("enum", NULL, RDP_T_enum, SCAN_P_IGNORE);
  scan_load_keyword("extends", NULL, RDP_T_extends, SCAN_P_IGNORE);
  scan_load_keyword("final", NULL, RDP_T_final, SCAN_P_IGNORE);
  scan_load_keyword("finally", NULL, RDP_T_finally, SCAN_P_IGNORE);
  scan_load_keyword("float", NULL, RDP_T_float, SCAN_P_IGNORE);
  scan_load_keyword("for", NULL, RDP_T_for, SCAN_P_IGNORE);
  scan_load_keyword("if", NULL, RDP_T_if, SCAN_P_IGNORE);
  scan_load_keyword("implements", NULL, RDP_T_implements, SCAN_P_IGNORE);
  scan_load_keyword("import", NULL, RDP_T_import, SCAN_P_IGNORE);
  scan_load_keyword("instanceof", NULL, RDP_T_instanceof, SCAN_P_IGNORE);
  scan_load_keyword("int", NULL, RDP_T_int, SCAN_P_IGNORE);
  scan_load_keyword("interface", NULL, RDP_T_interface, SCAN_P_IGNORE);
  scan_load_keyword("long", NULL, RDP_T_long, SCAN_P_IGNORE);
  scan_load_keyword("native", NULL, RDP_T_native, SCAN_P_IGNORE);
  scan_load_keyword("new", NULL, RDP_T_new, SCAN_P_IGNORE);
  scan_load_keyword("package", NULL, RDP_T_package, SCAN_P_IGNORE);
  scan_load_keyword("private", NULL, RDP_T_private, SCAN_P_IGNORE);
  scan_load_keyword("protected", NULL, RDP_T_protected, SCAN_P_IGNORE);
  scan_load_keyword("public", NULL, RDP_T_public, SCAN_P_IGNORE);
  scan_load_keyword("return", NULL, RDP_T_return, SCAN_P_IGNORE);
  scan_load_keyword("short", NULL, RDP_T_short, SCAN_P_IGNORE);
  scan_load_keyword("static", NULL, RDP_T_static, SCAN_P_IGNORE);
  scan_load_keyword("strictfp", NULL, RDP_T_strictfp, SCAN_P_IGNORE);
  scan_load_keyword("super", NULL, RDP_T_super, SCAN_P_IGNORE);
  scan_load_keyword("switch", NULL, RDP_T_switch, SCAN_P_IGNORE);
  scan_load_keyword("synchronized", NULL, RDP_T_synchronized, SCAN_P_IGNORE);
  scan_load_keyword("this", NULL, RDP_T_this, SCAN_P_IGNORE);
  scan_load_keyword("throw", NULL, RDP_T_throw, SCAN_P_IGNORE);
  scan_load_keyword("throws", NULL, RDP_T_throws, SCAN_P_IGNORE);
  scan_load_keyword("transient", NULL, RDP_T_transient, SCAN_P_IGNORE);
  scan_load_keyword("try", NULL, RDP_T_try, SCAN_P_IGNORE);
  scan_load_keyword("void", NULL, RDP_T_void, SCAN_P_IGNORE);
  scan_load_keyword("void.", NULL, RDP_T_11811110510046 /* void. */, SCAN_P_IGNORE);
  scan_load_keyword("void.c", NULL, RDP_T_1181111051004699 /* void.c */, SCAN_P_IGNORE);
  scan_load_keyword("void.cl", NULL, RDP_T_1181111051004699108 /* void.cl */, SCAN_P_IGNORE);
  scan_load_keyword("void.cla", NULL, RDP_T_118111105100469910897 /* void.cla */, SCAN_P_IGNORE);
  scan_load_keyword("void.clas", NULL, RDP_T_118111105100469910897115 /* void.clas */, SCAN_P_IGNORE);
  scan_load_keyword("void.class", NULL, RDP_T_118111105100469910897115115 /* void.class */, SCAN_P_IGNORE);
  scan_load_keyword("volatile", NULL, RDP_T_volatile, SCAN_P_IGNORE);
  scan_load_keyword("while", NULL, RDP_T_while, SCAN_P_IGNORE);
  scan_load_keyword("{", NULL, RDP_T_123 /* { */, SCAN_P_IGNORE);
  scan_load_keyword("|", NULL, RDP_T_124 /* | */, SCAN_P_IGNORE);
  scan_load_keyword("}", NULL, RDP_T_125 /* } */, SCAN_P_IGNORE);
  scan_load_keyword("~", NULL, RDP_T_126 /* ~ */, SCAN_P_IGNORE);
}

/* Set declarations */

  set_ lexerGrammar_first = SET_NULL;
  set_ lexerGrammar_stop = SET_NULL;
  set_ rdp_lexerGrammar_114_first = SET_NULL;
  set_ rdp_lexerGrammar_115_first = SET_NULL;

/* Initialise sets */

static void rdp_set_initialise(void)
{
  set_assign_list(&lexerGrammar_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, 
RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, 
RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, 
RDP_T_46 /* . */, RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_626262 /* >>> */, 
RDP_T_62626261 /* >>>= */, RDP_T_63 /* ? */, RDP_T_64 /* @ */, RDP_T_6511011011111697116105111110771011161041111007911467111110115116971101168210111511659 /* AnnotationMethodOrConstantRest; */, 
RDP_T_BooleanLiteral, RDP_T_CharacterLiteral, RDP_T_Expressions, RDP_T_FloatingPointLiteral, 
RDP_T_701111147311010511659 /* ForInit; */, RDP_T_ForUpdate, RDP_T_FormalParameter, 
RDP_T_IDENTIFIER, RDP_T_IntegerLiteral, RDP_T_NullLiteral, RDP_T_StringLiteral, 
RDP_T_TypeName, RDP_T_86971141059798108101681019910897114971161111141158210111511659 /* VariableDeclaratorsRest; */, 
RDP_T_91 /* [ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, RDP_T_abstract, 
RDP_T_assert, RDP_T_boolean, RDP_T_break, RDP_T_byte, RDP_T_case, RDP_T_catch, 
RDP_T_char, RDP_T_class, RDP_T_continue, RDP_T_default, RDP_T_do, RDP_T_double, 
RDP_T_else, RDP_T_enum, RDP_T_extends, RDP_T_final, RDP_T_finally, RDP_T_float, 
RDP_T_for, RDP_T_if, RDP_T_implements, RDP_T_import, RDP_T_instanceof, RDP_T_int, 
RDP_T_interface, RDP_T_long, RDP_T_native, RDP_T_new, RDP_T_package, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_return, RDP_T_short, RDP_T_static, RDP_T_strictfp, 
RDP_T_super, RDP_T_switch, RDP_T_synchronized, RDP_T_this, RDP_T_throw, RDP_T_throws, 
RDP_T_transient, RDP_T_try, RDP_T_void, RDP_T_118111105100469910897115115 /* void.class */, 
RDP_T_volatile, RDP_T_while, RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_125 /* } */, 
RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&lexerGrammar_stop, SCAN_P_EOF,SET_END);
  set_assign_list(&rdp_lexerGrammar_114_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, 
RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, 
RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, 
RDP_T_46 /* . */, RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_626262 /* >>> */, 
RDP_T_62626261 /* >>>= */, RDP_T_63 /* ? */, RDP_T_64 /* @ */, RDP_T_6511011011111697116105111110771011161041111007911467111110115116971101168210111511659 /* AnnotationMethodOrConstantRest; */, 
RDP_T_BooleanLiteral, RDP_T_CharacterLiteral, RDP_T_Expressions, RDP_T_FloatingPointLiteral, 
RDP_T_701111147311010511659 /* ForInit; */, RDP_T_ForUpdate, RDP_T_FormalParameter, 
RDP_T_IDENTIFIER, RDP_T_IntegerLiteral, RDP_T_NullLiteral, RDP_T_StringLiteral, 
RDP_T_TypeName, RDP_T_86971141059798108101681019910897114971161111141158210111511659 /* VariableDeclaratorsRest; */, 
RDP_T_91 /* [ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, RDP_T_abstract, 
RDP_T_assert, RDP_T_boolean, RDP_T_break, RDP_T_byte, RDP_T_case, RDP_T_catch, 
RDP_T_char, RDP_T_class, RDP_T_continue, RDP_T_default, RDP_T_do, RDP_T_double, 
RDP_T_else, RDP_T_enum, RDP_T_extends, RDP_T_final, RDP_T_finally, RDP_T_float, 
RDP_T_for, RDP_T_if, RDP_T_implements, RDP_T_import, RDP_T_instanceof, RDP_T_int, 
RDP_T_interface, RDP_T_long, RDP_T_native, RDP_T_new, RDP_T_package, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_return, RDP_T_short, RDP_T_static, RDP_T_strictfp, 
RDP_T_super, RDP_T_switch, RDP_T_synchronized, RDP_T_this, RDP_T_throw, RDP_T_throws, 
RDP_T_transient, RDP_T_try, RDP_T_void, RDP_T_118111105100469910897115115 /* void.class */, 
RDP_T_volatile, RDP_T_while, RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_125 /* } */, 
RDP_T_126 /* ~ */, SET_END);
  set_assign_list(&rdp_lexerGrammar_115_first, SCAN_P_ID, SCAN_P_INTEGER, SCAN_P_REAL, RDP_T_33 /* ! */, RDP_T_3361 /* != */, 
RDP_T_34 /* " */, RDP_T_37 /* % */, RDP_T_3761 /* %= */, RDP_T_38 /* & */, RDP_T_3838 /* && */, 
RDP_T_3861 /* &= */, RDP_T_39 /* ' */, RDP_T_40 /* ( */, RDP_T_41 /* ) */, RDP_T_42 /* * */, 
RDP_T_4261 /* *= */, RDP_T_43 /* + */, RDP_T_4343 /* ++ */, RDP_T_4361 /* += */, 
RDP_T_44 /* , */, RDP_T_45 /* - */, RDP_T_4545 /* -- */, RDP_T_4561 /* -= */, 
RDP_T_46 /* . */, RDP_T_464646 /* ... */, RDP_T_47 /* / */, RDP_T_4761 /* /= */, 
RDP_T_58 /* : */, RDP_T_59 /* ; */, RDP_T_60 /* < */, RDP_T_6060 /* << */, RDP_T_606061 /* <<= */, 
RDP_T_6061 /* <= */, RDP_T_61 /* = */, RDP_T_6161 /* == */, RDP_T_62 /* > */, 
RDP_T_6261 /* >= */, RDP_T_6262 /* >> */, RDP_T_626261 /* >>= */, RDP_T_626262 /* >>> */, 
RDP_T_62626261 /* >>>= */, RDP_T_63 /* ? */, RDP_T_64 /* @ */, RDP_T_6511011011111697116105111110771011161041111007911467111110115116971101168210111511659 /* AnnotationMethodOrConstantRest; */, 
RDP_T_BooleanLiteral, RDP_T_CharacterLiteral, RDP_T_Expressions, RDP_T_FloatingPointLiteral, 
RDP_T_701111147311010511659 /* ForInit; */, RDP_T_ForUpdate, RDP_T_FormalParameter, 
RDP_T_IDENTIFIER, RDP_T_IntegerLiteral, RDP_T_NullLiteral, RDP_T_StringLiteral, 
RDP_T_TypeName, RDP_T_86971141059798108101681019910897114971161111141158210111511659 /* VariableDeclaratorsRest; */, 
RDP_T_91 /* [ */, RDP_T_93 /* ] */, RDP_T_94 /* ^ */, RDP_T_9461 /* ^= */, RDP_T_abstract, 
RDP_T_assert, RDP_T_boolean, RDP_T_break, RDP_T_byte, RDP_T_case, RDP_T_catch, 
RDP_T_char, RDP_T_class, RDP_T_continue, RDP_T_default, RDP_T_do, RDP_T_double, 
RDP_T_else, RDP_T_enum, RDP_T_extends, RDP_T_final, RDP_T_finally, RDP_T_float, 
RDP_T_for, RDP_T_if, RDP_T_implements, RDP_T_import, RDP_T_instanceof, RDP_T_int, 
RDP_T_interface, RDP_T_long, RDP_T_native, RDP_T_new, RDP_T_package, RDP_T_private, 
RDP_T_protected, RDP_T_public, RDP_T_return, RDP_T_short, RDP_T_static, RDP_T_strictfp, 
RDP_T_super, RDP_T_switch, RDP_T_synchronized, RDP_T_this, RDP_T_throw, RDP_T_throws, 
RDP_T_transient, RDP_T_try, RDP_T_void, RDP_T_118111105100469910897115115 /* void.class */, 
RDP_T_volatile, RDP_T_while, RDP_T_123 /* { */, RDP_T_124 /* | */, RDP_T_125 /* } */, 
RDP_T_126 /* ~ */, SET_END);
}

/* Parser forward declarations and macros */
void lexerGrammar(void);

/* Parser functions */
void lexerGrammar(void)
{
  {
    if (scan_test_set(NULL, &rdp_lexerGrammar_114_first, NULL))
    { /* Start of rdp_lexerGrammar_114 */
      while (1)
      {
        {
          if (scan_test(NULL, SCAN_P_INTEGER, NULL))
          {
            scan_test(NULL, SCAN_P_INTEGER, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, SCAN_P_REAL, NULL))
          {
            scan_test(NULL, SCAN_P_REAL, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, SCAN_P_ID, NULL))
          {
            scan_test(NULL, SCAN_P_ID, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_34 /* " */, NULL))
          {
            scan_test(NULL, RDP_T_34 /* " */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_39 /* ' */, NULL))
          {
            scan_test(NULL, RDP_T_39 /* ' */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_33 /* ! */, NULL))
          {
            scan_test(NULL, RDP_T_33 /* ! */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_3361 /* != */, NULL))
          {
            scan_test(NULL, RDP_T_3361 /* != */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_37 /* % */, NULL))
          {
            scan_test(NULL, RDP_T_37 /* % */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_3761 /* %= */, NULL))
          {
            scan_test(NULL, RDP_T_3761 /* %= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_38 /* & */, NULL))
          {
            scan_test(NULL, RDP_T_38 /* & */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_3838 /* && */, NULL))
          {
            scan_test(NULL, RDP_T_3838 /* && */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_3861 /* &= */, NULL))
          {
            scan_test(NULL, RDP_T_3861 /* &= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_40 /* ( */, NULL))
          {
            scan_test(NULL, RDP_T_40 /* ( */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_41 /* ) */, NULL))
          {
            scan_test(NULL, RDP_T_41 /* ) */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_42 /* * */, NULL))
          {
            scan_test(NULL, RDP_T_42 /* * */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_4261 /* *= */, NULL))
          {
            scan_test(NULL, RDP_T_4261 /* *= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_43 /* + */, NULL))
          {
            scan_test(NULL, RDP_T_43 /* + */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_4343 /* ++ */, NULL))
          {
            scan_test(NULL, RDP_T_4343 /* ++ */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_4361 /* += */, NULL))
          {
            scan_test(NULL, RDP_T_4361 /* += */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_44 /* , */, NULL))
          {
            scan_test(NULL, RDP_T_44 /* , */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_45 /* - */, NULL))
          {
            scan_test(NULL, RDP_T_45 /* - */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_4545 /* -- */, NULL))
          {
            scan_test(NULL, RDP_T_4545 /* -- */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_4561 /* -= */, NULL))
          {
            scan_test(NULL, RDP_T_4561 /* -= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_46 /* . */, NULL))
          {
            scan_test(NULL, RDP_T_46 /* . */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_464646 /* ... */, NULL))
          {
            scan_test(NULL, RDP_T_464646 /* ... */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_47 /* / */, NULL))
          {
            scan_test(NULL, RDP_T_47 /* / */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_4761 /* /= */, NULL))
          {
            scan_test(NULL, RDP_T_4761 /* /= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_58 /* : */, NULL))
          {
            scan_test(NULL, RDP_T_58 /* : */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_59 /* ; */, NULL))
          {
            scan_test(NULL, RDP_T_59 /* ; */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_60 /* < */, NULL))
          {
            scan_test(NULL, RDP_T_60 /* < */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_6060 /* << */, NULL))
          {
            scan_test(NULL, RDP_T_6060 /* << */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_606061 /* <<= */, NULL))
          {
            scan_test(NULL, RDP_T_606061 /* <<= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_6061 /* <= */, NULL))
          {
            scan_test(NULL, RDP_T_6061 /* <= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_61 /* = */, NULL))
          {
            scan_test(NULL, RDP_T_61 /* = */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_6161 /* == */, NULL))
          {
            scan_test(NULL, RDP_T_6161 /* == */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_62 /* > */, NULL))
          {
            scan_test(NULL, RDP_T_62 /* > */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_6261 /* >= */, NULL))
          {
            scan_test(NULL, RDP_T_6261 /* >= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_6262 /* >> */, NULL))
          {
            scan_test(NULL, RDP_T_6262 /* >> */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_626261 /* >>= */, NULL))
          {
            scan_test(NULL, RDP_T_626261 /* >>= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_626262 /* >>> */, NULL))
          {
            scan_test(NULL, RDP_T_626262 /* >>> */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_62626261 /* >>>= */, NULL))
          {
            scan_test(NULL, RDP_T_62626261 /* >>>= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_63 /* ? */, NULL))
          {
            scan_test(NULL, RDP_T_63 /* ? */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_64 /* @ */, NULL))
          {
            scan_test(NULL, RDP_T_64 /* @ */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_6511011011111697116105111110771011161041111007911467111110115116971101168210111511659 /* AnnotationMethodOrConstantRest; */, NULL))
          {
            scan_test(NULL, RDP_T_6511011011111697116105111110771011161041111007911467111110115116971101168210111511659 /* AnnotationMethodOrConstantRest; */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_BooleanLiteral, NULL))
          {
            scan_test(NULL, RDP_T_BooleanLiteral, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_CharacterLiteral, NULL))
          {
            scan_test(NULL, RDP_T_CharacterLiteral, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_Expressions, NULL))
          {
            scan_test(NULL, RDP_T_Expressions, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_FloatingPointLiteral, NULL))
          {
            scan_test(NULL, RDP_T_FloatingPointLiteral, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_701111147311010511659 /* ForInit; */, NULL))
          {
            scan_test(NULL, RDP_T_701111147311010511659 /* ForInit; */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_ForUpdate, NULL))
          {
            scan_test(NULL, RDP_T_ForUpdate, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_FormalParameter, NULL))
          {
            scan_test(NULL, RDP_T_FormalParameter, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_IDENTIFIER, NULL))
          {
            scan_test(NULL, RDP_T_IDENTIFIER, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_IntegerLiteral, NULL))
          {
            scan_test(NULL, RDP_T_IntegerLiteral, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_NullLiteral, NULL))
          {
            scan_test(NULL, RDP_T_NullLiteral, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_StringLiteral, NULL))
          {
            scan_test(NULL, RDP_T_StringLiteral, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_TypeName, NULL))
          {
            scan_test(NULL, RDP_T_TypeName, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_86971141059798108101681019910897114971161111141158210111511659 /* VariableDeclaratorsRest; */, NULL))
          {
            scan_test(NULL, RDP_T_86971141059798108101681019910897114971161111141158210111511659 /* VariableDeclaratorsRest; */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_91 /* [ */, NULL))
          {
            scan_test(NULL, RDP_T_91 /* [ */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_93 /* ] */, NULL))
          {
            scan_test(NULL, RDP_T_93 /* ] */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_94 /* ^ */, NULL))
          {
            scan_test(NULL, RDP_T_94 /* ^ */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_9461 /* ^= */, NULL))
          {
            scan_test(NULL, RDP_T_9461 /* ^= */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_abstract, NULL))
          {
            scan_test(NULL, RDP_T_abstract, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_assert, NULL))
          {
            scan_test(NULL, RDP_T_assert, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_boolean, NULL))
          {
            scan_test(NULL, RDP_T_boolean, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_break, NULL))
          {
            scan_test(NULL, RDP_T_break, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_byte, NULL))
          {
            scan_test(NULL, RDP_T_byte, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_case, NULL))
          {
            scan_test(NULL, RDP_T_case, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_catch, NULL))
          {
            scan_test(NULL, RDP_T_catch, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_char, NULL))
          {
            scan_test(NULL, RDP_T_char, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_class, NULL))
          {
            scan_test(NULL, RDP_T_class, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_continue, NULL))
          {
            scan_test(NULL, RDP_T_continue, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_default, NULL))
          {
            scan_test(NULL, RDP_T_default, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_do, NULL))
          {
            scan_test(NULL, RDP_T_do, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_double, NULL))
          {
            scan_test(NULL, RDP_T_double, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_else, NULL))
          {
            scan_test(NULL, RDP_T_else, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_enum, NULL))
          {
            scan_test(NULL, RDP_T_enum, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_extends, NULL))
          {
            scan_test(NULL, RDP_T_extends, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_final, NULL))
          {
            scan_test(NULL, RDP_T_final, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_finally, NULL))
          {
            scan_test(NULL, RDP_T_finally, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_float, NULL))
          {
            scan_test(NULL, RDP_T_float, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_for, NULL))
          {
            scan_test(NULL, RDP_T_for, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_if, NULL))
          {
            scan_test(NULL, RDP_T_if, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_implements, NULL))
          {
            scan_test(NULL, RDP_T_implements, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_import, NULL))
          {
            scan_test(NULL, RDP_T_import, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_instanceof, NULL))
          {
            scan_test(NULL, RDP_T_instanceof, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_int, NULL))
          {
            scan_test(NULL, RDP_T_int, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_interface, NULL))
          {
            scan_test(NULL, RDP_T_interface, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_long, NULL))
          {
            scan_test(NULL, RDP_T_long, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_native, NULL))
          {
            scan_test(NULL, RDP_T_native, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_new, NULL))
          {
            scan_test(NULL, RDP_T_new, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_package, NULL))
          {
            scan_test(NULL, RDP_T_package, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_private, NULL))
          {
            scan_test(NULL, RDP_T_private, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_protected, NULL))
          {
            scan_test(NULL, RDP_T_protected, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_public, NULL))
          {
            scan_test(NULL, RDP_T_public, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_return, NULL))
          {
            scan_test(NULL, RDP_T_return, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_short, NULL))
          {
            scan_test(NULL, RDP_T_short, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_static, NULL))
          {
            scan_test(NULL, RDP_T_static, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_strictfp, NULL))
          {
            scan_test(NULL, RDP_T_strictfp, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_super, NULL))
          {
            scan_test(NULL, RDP_T_super, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_switch, NULL))
          {
            scan_test(NULL, RDP_T_switch, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_synchronized, NULL))
          {
            scan_test(NULL, RDP_T_synchronized, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_this, NULL))
          {
            scan_test(NULL, RDP_T_this, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_throw, NULL))
          {
            scan_test(NULL, RDP_T_throw, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_throws, NULL))
          {
            scan_test(NULL, RDP_T_throws, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_transient, NULL))
          {
            scan_test(NULL, RDP_T_transient, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_try, NULL))
          {
            scan_test(NULL, RDP_T_try, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_void, NULL))
          {
            scan_test(NULL, RDP_T_void, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_118111105100469910897115115 /* void.class */, NULL))
          {
            scan_test(NULL, RDP_T_118111105100469910897115115 /* void.class */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_volatile, NULL))
          {
            scan_test(NULL, RDP_T_volatile, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_while, NULL))
          {
            scan_test(NULL, RDP_T_while, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_123 /* { */, NULL))
          {
            scan_test(NULL, RDP_T_123 /* { */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_124 /* | */, NULL))
          {
            scan_test(NULL, RDP_T_124 /* | */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_125 /* } */, NULL))
          {
            scan_test(NULL, RDP_T_125 /* } */, &lexerGrammar_stop);
            scan_();
          }
          else
          if (scan_test(NULL, RDP_T_126 /* ~ */, NULL))
          {
            scan_test(NULL, RDP_T_126 /* ~ */, &lexerGrammar_stop);
            scan_();
          }
          else
            scan_test_set(NULL, &rdp_lexerGrammar_114_first, &lexerGrammar_stop)          ;
          }
        if (!scan_test_set(NULL, &rdp_lexerGrammar_114_first, NULL)) break;
      }
    } /* end of rdp_lexerGrammar_114 */
    scan_test_set(NULL, &lexerGrammar_stop, &lexerGrammar_stop);
   }
}

int main(int argc, char *argv[])
{
  clock_t rdp_finish_time, rdp_start_time = clock();
  int
    rdp_symbol_statistics = 0,    /* show symbol_ table statistics flag */
    rdp_line_echo_all = 0,        /* make a listing on all passes flag */
    rdp_filter = 0,               /* filter flag */
    rdp_line_echo = 0,            /* make listing flag */

    rdp_lexicalise = 0;            /* print lexicalised output flag */

  unsigned long rdp_textsize = 35000l;   /* size of scanner text array */

  unsigned long rdp_tabwidth = 8l;   /* tab expansion width */

  char* rdp_vcg_filename = NULL;      /* filename for -V option */

  arg_message("rdparser\n" RDP_STAMP "\n\n""Usage: java_lex [options] source");

  arg_message("");
  arg_boolean('f', "Filter mode (read from stdin and write to stdout)", &rdp_filter);
  arg_boolean('l', "Make a listing", &rdp_line_echo);
  arg_boolean('L', "Print lexicalised source file", &rdp_lexicalise);
  arg_string ('o', "Write output to filename", &rdp_outputfilename);
  arg_boolean('s', "Echo each scanner symbol as it is read", &rdp_symbol_echo);
  arg_boolean('S', "Print summary symbol table statistics", &rdp_symbol_statistics);
  arg_numeric('t', "Tab expansion width (default 8)", &rdp_tabwidth);
  arg_numeric('T', "Text buffer size in bytes for scanner (default 20000)", &rdp_textsize);
  arg_boolean('v', "Set verbose mode", &rdp_verbose);
  arg_string ('V', "Write derivation tree to filename in VCG format", &rdp_vcg_filename);

  rdp_sourcefilenames = arg_process(argc, argv);

  /* Fix up filetypes */
  for (rdp_sourcefilenumber = 0; rdp_sourcefilenames[rdp_sourcefilenumber] != NULL; rdp_sourcefilenumber++)
    rdp_sourcefilenames[rdp_sourcefilenumber] = text_default_filetype(rdp_sourcefilenames[rdp_sourcefilenumber], "");

  if (rdp_filter)
  {
    rdp_sourcefilenames[0] = "-";
    rdp_outputfilename = "-";
    rdp_sourcefilenames[1] = NULL;     /* make sure no further filenames are taken from the array */

  }
  if ((rdp_sourcefilename = rdp_sourcefilenames[0]) == NULL)
     arg_help("no source files specified");

  if (rdp_sourcefilenames[1] != NULL)
    arg_help("multiple source files not allowed\n");
  text_init(rdp_textsize, 25, 100, (int) rdp_tabwidth);
  scan_init(0, 0, 0, rdp_symbol_echo, rdp_tokens);
  if (rdp_lexicalise)
    scan_lexicalise();
  rdp_set_initialise();
  rdp_load_keywords();
  if (rdp_verbose)
     text_printf("\nrdparser\n" RDP_STAMP "\n\n");
  for (rdp_pass = 1; rdp_pass <= RDP_PASSES; rdp_pass++)
  {
    text_echo(rdp_line_echo_all || (rdp_line_echo && rdp_pass == RDP_PASSES));

    for (rdp_sourcefilenumber = 0; (rdp_sourcefilename = rdp_sourcefilenames[rdp_sourcefilenumber]) != NULL; rdp_sourcefilenumber++)
    {
      if (text_open(rdp_sourcefilename) == NULL)
        arg_help("unable to open source file");

      text_get_char();
      scan_();

      lexerGrammar();            /* call parser at top level */
      if (text_total_errors() != 0)
        text_message(TEXT_FATAL, "error%s detected in source file '%s'\n", text_total_errors() == 1 ? "" : "s", rdp_sourcefilename);   /* crash quietly */ 
    }
  }

  rdp_sourcefilename = rdp_sourcefilenames[0];     /* Reset filename to first file in the list */

  if (rdp_symbol_statistics)
  {
    symbol_print_all_table_statistics(11);
    symbol_print_all_table();

  }
  text_print_total_errors();
  if (rdp_verbose)
  {
    rdp_finish_time = clock();
    text_message(TEXT_INFO, "%.3f CPU seconds used\n", ((double) (rdp_finish_time-rdp_start_time)) / CLOCKS_PER_SEC);
  }
  return rdp_error_return;
}

/* End of java_lex.c */
