#ifndef TEXTLEVEL_H
#define TEXTLEVEL_H

enum TextLevel {
  TL_FATAL, TL_ERROR, TL_WARNING, TL_INFO, TL_TRACE, TL_OUTPUT, TL_FATAL_ECHO, TL_ERROR_ECHO, TL_WARNING_ECHO, TL_INFO_ECHO, TL_TRACE_ECHO, TL_OUTPUT_ECHO
};
#endif
