/*******************************************************************************
*
* Header file generated by RDP on May 16 2016 14:55:49 from tg.bnf
*
*******************************************************************************/
#ifndef TG_H
#define TG_H

#include "arg.h"
#include "graph.h"
#include "hist.h"
#include "memalloc.h"
#include "scan.h"
#include "set.h"
#include "symbol.h"
#include "textio.h"


/* Maximum number of passes */
#define RDP_PASSES 1

/* Time and date stamp */
#define RDP_STAMP "Generated on May 16 2016 14:55:49 and compiled on " __DATE__ " at " __TIME__ 

/* Token enumeration */
enum
{
RDP_TT_BOTTOM = SCAN_P_TOP,
RDP_T_36 /* $ */ = SCAN_P_TOP,RDP_T_40 /* ( */,RDP_T_4042 /* (* */,RDP_T_accept,RDP_T_reject,RDP_T_123 /* { */,
RDP_TT_TOP
};

/* Tree data types */

typedef struct rdp_tree_node_data_struct
{
  SCAN_DATA
  
} rdp_tree_node_data;
typedef struct rdp_tree_edge_data_struct
{
  int rdp_edge_kind;
  
} rdp_tree_edge_data;

/* Symbol table support */
/* Parser start production */
void tests(void);



#endif

/* End of tg.h */
